// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fit_stump
List fit_stump(NumericMatrix X, NumericVector residuals);
RcppExport SEXP _GradBoostR_fit_stump(SEXP XSEXP, SEXP residualsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type residuals(residualsSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_stump(X, residuals));
    return rcpp_result_gen;
END_RCPP
}
// gbm_predict
NumericVector gbm_predict(const NumericMatrix& X, const List& stumps, double learning_rate, double init_value);
RcppExport SEXP _GradBoostR_gbm_predict(SEXP XSEXP, SEXP stumpsSEXP, SEXP learning_rateSEXP, SEXP init_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const List& >::type stumps(stumpsSEXP);
    Rcpp::traits::input_parameter< double >::type learning_rate(learning_rateSEXP);
    Rcpp::traits::input_parameter< double >::type init_value(init_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(gbm_predict(X, stumps, learning_rate, init_value));
    return rcpp_result_gen;
END_RCPP
}
// grad_boost_fit
List grad_boost_fit(const arma::mat& X, const arma::vec& y, double learning_rate, int n_trees);
RcppExport SEXP _GradBoostR_grad_boost_fit(SEXP XSEXP, SEXP ySEXP, SEXP learning_rateSEXP, SEXP n_treesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type learning_rate(learning_rateSEXP);
    Rcpp::traits::input_parameter< int >::type n_trees(n_treesSEXP);
    rcpp_result_gen = Rcpp::wrap(grad_boost_fit(X, y, learning_rate, n_trees));
    return rcpp_result_gen;
END_RCPP
}
// nn_train_arma
List nn_train_arma(const arma::mat& X, const arma::vec& y, int hidden_units, int epochs, double learning_rate);
RcppExport SEXP _GradBoostR_nn_train_arma(SEXP XSEXP, SEXP ySEXP, SEXP hidden_unitsSEXP, SEXP epochsSEXP, SEXP learning_rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type hidden_units(hidden_unitsSEXP);
    Rcpp::traits::input_parameter< int >::type epochs(epochsSEXP);
    Rcpp::traits::input_parameter< double >::type learning_rate(learning_rateSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_train_arma(X, y, hidden_units, epochs, learning_rate));
    return rcpp_result_gen;
END_RCPP
}
// nn_predict_model
arma::vec nn_predict_model(const arma::mat& X, List model);
RcppExport SEXP _GradBoostR_nn_predict_model(SEXP XSEXP, SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_predict_model(X, model));
    return rcpp_result_gen;
END_RCPP
}
// nn_predict_arma
NumericVector nn_predict_arma(const arma::mat& X, const arma::mat& W1, const arma::vec& b1, const arma::mat& W2, const arma::vec& b2, bool classification);
RcppExport SEXP _GradBoostR_nn_predict_arma(SEXP XSEXP, SEXP W1SEXP, SEXP b1SEXP, SEXP W2SEXP, SEXP b2SEXP, SEXP classificationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W1(W1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b1(b1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W2(W2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b2(b2SEXP);
    Rcpp::traits::input_parameter< bool >::type classification(classificationSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_predict_arma(X, W1, b1, W2, b2, classification));
    return rcpp_result_gen;
END_RCPP
}
// rf_class_fit_fast
Rcpp::List rf_class_fit_fast(const arma::mat& X, const arma::vec& y, int n_trees, int max_depth, int mtry, bool use_gini);
RcppExport SEXP _GradBoostR_rf_class_fit_fast(SEXP XSEXP, SEXP ySEXP, SEXP n_treesSEXP, SEXP max_depthSEXP, SEXP mtrySEXP, SEXP use_giniSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_trees(n_treesSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< int >::type mtry(mtrySEXP);
    Rcpp::traits::input_parameter< bool >::type use_gini(use_giniSEXP);
    rcpp_result_gen = Rcpp::wrap(rf_class_fit_fast(X, y, n_trees, max_depth, mtry, use_gini));
    return rcpp_result_gen;
END_RCPP
}
// rf_class_predict_fast
arma::vec rf_class_predict_fast(const arma::mat& X, Rcpp::List forest_list);
RcppExport SEXP _GradBoostR_rf_class_predict_fast(SEXP XSEXP, SEXP forest_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type forest_list(forest_listSEXP);
    rcpp_result_gen = Rcpp::wrap(rf_class_predict_fast(X, forest_list));
    return rcpp_result_gen;
END_RCPP
}
// rf_fit_fast
Rcpp::List rf_fit_fast(const arma::mat& X, const arma::vec& y, int n_trees, int max_depth, int mtry);
RcppExport SEXP _GradBoostR_rf_fit_fast(SEXP XSEXP, SEXP ySEXP, SEXP n_treesSEXP, SEXP max_depthSEXP, SEXP mtrySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_trees(n_treesSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< int >::type mtry(mtrySEXP);
    rcpp_result_gen = Rcpp::wrap(rf_fit_fast(X, y, n_trees, max_depth, mtry));
    return rcpp_result_gen;
END_RCPP
}
// rf_predict_fast
arma::vec rf_predict_fast(const arma::mat& X, Rcpp::List forest_list);
RcppExport SEXP _GradBoostR_rf_predict_fast(SEXP XSEXP, SEXP forest_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type forest_list(forest_listSEXP);
    rcpp_result_gen = Rcpp::wrap(rf_predict_fast(X, forest_list));
    return rcpp_result_gen;
END_RCPP
}
// rf_predict_fast_class
IntegerVector rf_predict_fast_class(const arma::mat& X, const List& forest_list);
RcppExport SEXP _GradBoostR_rf_predict_fast_class(SEXP XSEXP, SEXP forest_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const List& >::type forest_list(forest_listSEXP);
    rcpp_result_gen = Rcpp::wrap(rf_predict_fast_class(X, forest_list));
    return rcpp_result_gen;
END_RCPP
}
// rf_predict_fast_class_prob
NumericMatrix rf_predict_fast_class_prob(const arma::mat& X, const List& forest_list, int n_classes);
RcppExport SEXP _GradBoostR_rf_predict_fast_class_prob(SEXP XSEXP, SEXP forest_listSEXP, SEXP n_classesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const List& >::type forest_list(forest_listSEXP);
    Rcpp::traits::input_parameter< int >::type n_classes(n_classesSEXP);
    rcpp_result_gen = Rcpp::wrap(rf_predict_fast_class_prob(X, forest_list, n_classes));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GradBoostR_fit_stump", (DL_FUNC) &_GradBoostR_fit_stump, 2},
    {"_GradBoostR_gbm_predict", (DL_FUNC) &_GradBoostR_gbm_predict, 4},
    {"_GradBoostR_grad_boost_fit", (DL_FUNC) &_GradBoostR_grad_boost_fit, 4},
    {"_GradBoostR_nn_train_arma", (DL_FUNC) &_GradBoostR_nn_train_arma, 5},
    {"_GradBoostR_nn_predict_model", (DL_FUNC) &_GradBoostR_nn_predict_model, 2},
    {"_GradBoostR_nn_predict_arma", (DL_FUNC) &_GradBoostR_nn_predict_arma, 6},
    {"_GradBoostR_rf_class_fit_fast", (DL_FUNC) &_GradBoostR_rf_class_fit_fast, 6},
    {"_GradBoostR_rf_class_predict_fast", (DL_FUNC) &_GradBoostR_rf_class_predict_fast, 2},
    {"_GradBoostR_rf_fit_fast", (DL_FUNC) &_GradBoostR_rf_fit_fast, 5},
    {"_GradBoostR_rf_predict_fast", (DL_FUNC) &_GradBoostR_rf_predict_fast, 2},
    {"_GradBoostR_rf_predict_fast_class", (DL_FUNC) &_GradBoostR_rf_predict_fast_class, 2},
    {"_GradBoostR_rf_predict_fast_class_prob", (DL_FUNC) &_GradBoostR_rf_predict_fast_class_prob, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_GradBoostR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
