# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit_stump <- function(X, residuals) {
    .Call(`_GradBoostR_fit_stump`, X, residuals)
}

gbm_predict <- function(X, stumps, learning_rate, init_value) {
    .Call(`_GradBoostR_gbm_predict`, X, stumps, learning_rate, init_value)
}

grad_boost_fit <- function(X, y, learning_rate, n_trees) {
    .Call(`_GradBoostR_grad_boost_fit`, X, y, learning_rate, n_trees)
}

nn_train_arma <- function(X, y, hidden_units = 32L, epochs = 50L, lr = 0.01) {
    .Call(`_GradBoostR_nn_train_arma`, X, y, hidden_units, epochs, lr)
}

nn_predict_model <- function(X, model) {
    .Call(`_GradBoostR_nn_predict_model`, X, model)
}

nn_predict_arma <- function(X, W1, b1, W2, b2, classification = FALSE) {
    .Call(`_GradBoostR_nn_predict_arma`, X, W1, b1, W2, b2, classification)
}

rf_class_fit_fast <- function(X, y, n_trees = 100L, max_depth = 5L, mtry = 3L, use_gini = TRUE) {
    .Call(`_GradBoostR_rf_class_fit_fast`, X, y, n_trees, max_depth, mtry, use_gini)
}

rf_class_predict_fast <- function(X, forest_list) {
    .Call(`_GradBoostR_rf_class_predict_fast`, X, forest_list)
}

rf_fit_fast <- function(X, y, n_trees = 200L, max_depth = 5L, mtry = 3L) {
    .Call(`_GradBoostR_rf_fit_fast`, X, y, n_trees, max_depth, mtry)
}

rf_predict_fast <- function(X, forest_list) {
    .Call(`_GradBoostR_rf_predict_fast`, X, forest_list)
}

rf_predict_fast_class <- function(X, forest_list) {
    .Call(`_GradBoostR_rf_predict_fast_class`, X, forest_list)
}

rf_predict_fast_class_prob <- function(X, forest_list, n_classes) {
    .Call(`_GradBoostR_rf_predict_fast_class_prob`, X, forest_list, n_classes)
}

